### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Nebula7388** [AdvancedXRay/XRay-Mod#219]
Whenever I toggle x-ray my game crashes

**Comment by MichaelHillcox** [comment]
Attach a crash report

**Comment by comonier** [comment]
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.gui.components.Button.<init>(net.minecraft.client.gui.components.Button$Builder)'

log:
https://paste.ofcode.org/AEXkGTkSH99Fv7wZxZhEx4

mods:
![image](https://user-images.githubusercontent.com/19571541/211105934-035dd069-34df-46ba-a4cb-a6b5e95bd67d.png)

**Comment by comonier** [comment]
Strange Crash log saying it is 1.19.2 when it is 1.19.3

![image](https://user-images.githubusercontent.com/19571541/211106089-852d732a-028c-4f07-8ec4-9e24a1dd3e58.png)

**Comment by comonier** [comment]
**ITS CRASHING WHEN WE CLICK ON XRAY OPTION KEYBINDING**

**Comment by comonier** [comment]
I'm server administrator and i use it mod to check if my anti-xray is working fine **TY FOR IT** but that last build is crasking the game when it try to open config menu.

**Comment by comonier** [comment]
> Whenever I toggle x-ray my game crashes

in my case toggle not crash my client only [ Open XRay Menu ] option crash

**Comment by MichaelHillcox** [comment]
Sorry, your log is no longer available. Can you post it again? Maybe use gist.github.com

**Comment by enormousbun** [comment]
Crash report: 
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-03-05 10:08:57
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.client.gui.components.Button$Builder pro.mikey.xray.gui.utils.SupportButton.m_253074_(net.minecraft.network.chat.Component, net.minecraft.client.gui.components.Button$OnPress)'
	at pro.mikey.xray.gui.utils.SupportButton.<init>(SupportButton.java:16) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.gui.GuiSelectionScreen$SupportButtonInner.<init>(GuiSelectionScreen.java:238) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.gui.GuiSelectionScreen.m_7856_(GuiSelectionScreen.java:93) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_232761_(Screen.java:421) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:411) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:974) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at pro.mikey.xray.keybinding.KeyBindings.eventInput(KeyBindings.java:40) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.keybinding.__KeyBindings_eventInput_InputEvent.invoke(.dynamic) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onKeyInput(ForgeHooksClient.java:753) ~[forge-1.19.2-43.2.0-universal.jar%23152!/:?] {re:classloading}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:407) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pro.mikey.xray.gui.utils.SupportButton.<init>(SupportButton.java:16) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.gui.GuiSelectionScreen$SupportButtonInner.<init>(GuiSelectionScreen.java:238) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.gui.GuiSelectionScreen.m_7856_(GuiSelectionScreen.java:93) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_232761_(Screen.java:421) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:411) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:974) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at pro.mikey.xray.keybinding.KeyBindings.eventInput(KeyBindings.java:40) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading}
	at pro.mikey.xray.keybinding.__KeyBindings_eventInput_InputEvent.invoke(.dynamic) ~[advanced-xray-forge-1.19.3-2.14.0-build.16.jar%23146!/:1.19.3-2.14.0-build.16] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onKeyInput(ForgeHooksClient.java:753) ~[forge-1.19.2-43.2.0-universal.jar%23152!/:?] {re:classloading}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:407) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['enormousbun'/141, l='ClientLevel', x=-291.21, y=-45.00, z=-593.82]]
	Chunk stats: 2601, 228
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,114,16), Section: (at 0,2,0 in 0,7,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 40662 game time, 17733 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23147!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, VanillaTweaks-NoSpawns, undefined-Totem-pv9

Same error, whenever I press the *correct* key for the x-ray gui *that i bound manually* the world freezes for a second, a screen pops up and says "Saving world" and the game crashes. Please help.
