### ISSUE TITLE
crash with The Aether in 1.20.4 neoforge

### ISSUE THREAD

**Issue by Logite-c** [AdvancedXRay/XRay-Mod#269]
**Describe the bug**
cant load
**To Reproduce**
1. step one install aether mod and xray in 1.20.4
2. execute
**Expected behavior**

**Minecraft Enviorment**
 - Minecraft Version: 1.20.4
 - XRay Mod Version: advanced-xray-neoforge-84.0.0.jar
neoforge 20.4.234

-- Head --
Thread: Render thread
Stacktrace:
	at net.neoforged.neoforge.registries.DeferredHolder.bind(DeferredHolder.java:154) ~[neoforge-20.4.234-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at net.neoforged.neoforge.registries.DeferredHolder.value(DeferredHolder.java:100) ~[neoforge-20.4.234-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at net.neoforged.neoforge.registries.DeferredHolder.get(DeferredHolder.java:116) ~[neoforge-20.4.234-universal.jar%23328!/:?] {re:mixin,re:classloading}
	at com.aetherteam.cumulus.client.event.hooks.MenuHooks.prepareCustomMenus(MenuHooks.java:42) ~[cumulus_menus-1.20.4-1.0.1-neoforge.jar%23343!/:1.20.4-1.0.1-neoforge] {re:classloading}
	at com.aetherteam.cumulus.client.event.listeners.MenuListener.onGuiOpenHighest(MenuListener.java:25) ~[cumulus_menus-1.20.4-1.0.1-neoforge.jar%23343!/:1.20.4-1.0.1-neoforge] {re:classloading}
	at net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:81) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:386) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.neoforged.bus.EventBus.post(EventBus.java:351) ~[bus-7.2.0.jar%23104!/:?] {}
	at net.minecraft.client.Minecraft.setScreen(Minecraft.java:1108) ~[client-1.20.4-20231207.154220-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod embeddium_extra,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:621) ~[client-1.20.4-20231207.154220-srg.jar%23327!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.world_leaks.MinecraftMixin from mod modernfix,pl:mixin:APP:modernfix-neoforge.mixins.json:feature.measure_time.MinecraftMixin_Forge from mod modernfix,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:immediatelyfast-common.mixins.json:core.MixinMinecraftClient from mod immediatelyfast,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor from mod embeddium_extra,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by MichaelHillcox** [comment]
Please attach the full crashlog

**Comment by Logite-c** [comment]
[crash-2024-05-22_10.45.00-fml.txt](https://github.com/AdvancedXRay/XRay-Mod/files/15397031/crash-2024-05-22_10.45.00-fml.txt)
[latest.log](https://github.com/AdvancedXRay/XRay-Mod/files/15397034/latest.log)
okay here is full log

**Comment by MichaelHillcox** [comment]
This should have been fixed as of `84.0.1`
